version: '3'
services:
  api:
    container_name: go_api
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: golang
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./tmp/db/data:/var/lib/mysql
    ports:
      - 3333:3306
